### ISSUE TITLE
invitation for ctb role - tidygate uses some of the gatepoints functions

### ISSUE THREAD

**Issue by stemangiola** [wjawaid/gatepoints#2]
Hello,

I am publishing on CRAN a package tidygate (https://github.com/stemangiola/tidygate), that uses your gatepoints package. Not only, but I had to copy applyGate function because of a functionality that i offer and because it is hidden in your package,

So I would like to invite you as co-author with a ctb role.

Let me know what you think.

Thanks for your package.
Stefano

**Comment by wjawaid** [comment]
Hi Stefano,

That's great. Thanks for letting me know. Please do include me as a co-author.

Best wishes,
Wajid
