### ISSUE TITLE
CRAN wants your attention - they wrote to me

### ISSUE THREAD

**Issue by stemangiola** [wjawaid/gatepoints#3]
On 16/01/2021 15:41, Prof Brian Ripley wrote:
> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_tidygate.html>.
> 
> Please correct before 2021-01-30 to safely retain your package on CRAN.
> 
> The CRAN Team

The former maintainer of gatepoints has not updated the address in the 
package and mail is returned.  It has been archivedand so tidygate 
cannot be installed.  It is open to you to take over gatepoints (regard 
it a formally orphaned): only your package is affected and will also 
need to be archived unless this is resolved by the deadline above.

-- 
Brian D. Ripley,                  ripley@stats.ox.ac.uk
Emeritus Professor of Applied Statistics, University of Oxford

**Comment by stemangiola** [comment]
Hello Again,

a solution can be I incorporate the code to tidygate and drop the dependency. Since you are an author on tidygate as well I think it could be an OK solution.

Please let me know what you think.

https://github.com/stemangiola/tidygate/pull/10

**Comment by wjawaid** [comment]
Thanks. I've submitted an update. Waiting for CRAN to accept.
