### ISSUE TITLE
error in applyGate function

### ISSUE THREAD

**Issue by ProfBiscuit** [wjawaid/gatepoints#4]
I am attempting to use the _gatepoints_ package to determine the coordinates of anatomical regions of interest for my research. The target of the application of your code are the generated body maps from the _gganatogram_ package. 

The following code ends with the error "Error in if (v[j, 1] != v[k, 1]) { : missing value where TRUE/FALSE needed". 

Do you have any suggestions for what I need to do or how to address the error? Any suggestions will be greatly appreciated.

```
devtools::install_github("jespermaag/gganatogram")
library(gganatogram)
library(gatepoints)
library(dplyr)

p0 <- gganatogram(ggplot2_only = T) 
p0
p0_data <- p0$data %>% select(x, y)
rownames(p0_data) <- 1:nrow(p0_data)

plot(p0_data, col = "blue", type = "l")
right_hand <- fhs(data = p0_data, 
                              names = F,
                              mark = T
                              )
```

Thank you for your time,

Biscuit

**Comment by wjawaid** [comment]
@ProfBiscuit I'm not familiar with ggnatogram. Having had  a look at the GitHub - this uses ggplot for plotting and gatepoints will not work as it only works with base graphics. Please correct me if I'm wrong?

There is another package called 'tidygate' - this is based on gatepoints code but works in ggplot. I'll leave the issue open for now. Please let me know if you have a solution.
